version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ia-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-ia
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file" # Define o driver de log como json-file

volumes:
  .postgres-data:
