export const TRANSACTION_CATEGORY_LABEL = {
  EDUCATION: "EDUCAÇÃO",
  ENTERTAINMENT: "ENTRETENIMENTO",
  FOOD: "ALIMENTAÇÃO",
  HEALTH: "SAUDE",
  HOUSING: "MORADIA",
  OTHER: "OUTROS",
  SALARY: "SALÁRIO",
  TRANSPORTATION: "TRANSPORTE",
  UTILITY: "UTILIDADES",
};

export const TRANSACTION_PAYMENT_METHOD_LABEL = {
  BANK_TRANSFER: "TRANSFERÊNCIA BANCÁRIA",
  BANK_SLIP: "BOLETO BANCÁRIO",
  CASH: "DINHEIRO",
  CREDIT_CARD: "CARTÃO DE CRÉDITO",
  DEBIT_CARD: "CARTÃO DE DÉBITO",
  OTHER: "OUTROS",
  PIX: "PIX",
};
